update-time: 5
gui-name: '&c&lCrops Top'
gui-name-sugar_cane_block: '&cSugarcane Top &7&o(#1-#9)'
gui-name-cactus: '&cCactus Top &7&o(#1-#9)'
gui-name-wheat: '&cWheat Top &7&o(#1-#9)'
gui-name-pumpkin: '&cPumpkin Top &7&o(#1-#9)'
gui-name-melon: '&cMelon Top &7&o(#1-#9)'
gui-name-carrot: '&cCarrot Top &7&o(#1-#9)'
gui-name-potato: '&cPotato Top &7&o(#1-#9)'
gui-item-name: '&c&n{crop} Top'
gui-item-lore:
 - '&fClick to view the top players'
 - '&ffor breaking {crop}'
 - ''
 - '&cYour Current: &f&n{broken}'
no-stats-exist: '&cThere are no stats for &c&n{crop}'
no-perms: '&cYou do not have permission for this!'
updated: '&cCropsTop list has been force updated!'